/** Deterministic fixtures shaped exactly like real engine payloads. */

import type {
  ArrangementDto,
  EnvironmentDto,
  InstrumentDto,
  KeymapDto,
  SourceDto,
} from '@shawzify/shared-types';

export const sourceFixture: SourceDto = {
  sourceId: 'abc123:audio',
  kind: 'audio',
  title: 'Demo Melody',
  durationSeconds: 30,
  noteCount: 73,
  bpm: 96,
  bpmConfidence: 0.82,
  key: {
    tonicPitchClass: 0,
    tonic: 'C',
    mode: 'major',
    name: 'C Major',
    confidence: 0.71,
    correlation: 0.83,
    runnerUp: 'A Minor',
  },
  transcriptionBackend: 'basic_pitch',
  stemUsed: 'vocals',
  contentHash: 'abc123def456',
  warnings: [],
  waveform: {
    min: Array.from({ length: 64 }, (_, i) => -Math.abs(Math.sin(i / 5)) * 0.8),
    max: Array.from({ length: 64 }, (_, i) => Math.abs(Math.sin(i / 5)) * 0.8),
    rms: Array.from({ length: 64 }, (_, i) => Math.abs(Math.sin(i / 5)) * 0.4),
    buckets: 64,
    durationSeconds: 30,
    sampleRate: 44100,
  },
  analysis: {
    durationSeconds: 30,
    tempoBpm: 96,
    tempoConfidence: 0.82,
    key: 'C',
    mode: 'major',
    keyConfidence: 0.71,
    timeSignatureEstimate: '4/4',
    energy: 0.21,
    onsetDensity: 2.4,
    pitchRange: [48, 84],
    polyphonyEstimate: 2.1,
    backend: 'librosa',
  },
  events: [
    {
      pitchMidi: 72,
      pitchName: 'C5',
      startSeconds: 0,
      durationSeconds: 0.5,
      velocity: 0.9,
      confidence: 1,
      source: 'demo',
      voice: 0,
    },
    {
      pitchMidi: 76,
      pitchName: 'E5',
      startSeconds: 0.625,
      durationSeconds: 0.5,
      velocity: 0.8,
      confidence: 1,
      source: 'demo',
      voice: 0,
    },
    {
      pitchMidi: 91,
      pitchName: 'G6',
      startSeconds: 1.25,
      durationSeconds: 0.5,
      velocity: 0.8,
      confidence: 1,
      source: 'demo',
      voice: 0,
    },
  ],
};

export const arrangementFixture: ArrangementDto = {
  sourceId: 'abc123:audio',
  code: '5SAAhAKkAUhAeUAo',
  song: {
    scaleId: 'maj',
    events: [
      { tick: 0, fret: '2', string: '2', position: '2-2' },
      { tick: 10, fret: '3', string: '1', position: '3-1' },
    ],
    noteCount: 2,
    endTick: 10,
  },
  resolved: {
    mode: 'balanced',
    scaleId: 'maj',
    scaleName: 'Major',
    transpose: -12,
    quantization: '1/8',
    quantizationStrength: 0.85,
    maxDensity: 8.2,
    arpeggiateChords: true,
    leadInTicks: 44,
    focus: 'full',
    focusWindow: null,
    detail: { observedDensity: 3.1, peakDensityAfter: 2.8, scaleScore: 91.2 },
  },
  report: {
    detectedKey: 'C Major',
    keyConfidence: 0.71,
    detectedBpm: 96,
    bpmConfidence: 0.82,
    scaleId: 'maj',
    scaleName: 'Major',
    transpose: -12,
    compatibilityBefore: {
      pitch_coverage: 61,
      melody_preservation: 55,
      rhythm_preservation: 88,
      harmony_preservation: 70,
      overall: 50.9,
    },
    compatibilityAfter: {
      pitch_coverage: 79,
      melody_preservation: 98.3,
      rhythm_preservation: 96.1,
      harmony_preservation: 96.6,
      overall: 90.7,
    },
    metrics: {
      sourceNotes: 73,
      outputNotes: 61,
      removedNotes: 12,
      movedNotes: 40,
      octaveFoldedNotes: 14,
      arpeggiatedNotes: 3,
      chordSubstitutions: 0,
      averagePitchError: 0.9,
      weightedPitchError: 0.7,
      timingErrorMean: 0.012,
      timingErrorMax: 0.05,
      melodyRetention: 0.98,
    },
    warnings: ['12 notes were removed to fit the Shawzin (16.4% of the source).'],
    durationSeconds: 29.5,
    stageTimings: [{ stage: 'arrange', durationSeconds: 0.08, success: true, detail: {} }],
    scaleCandidates: [
      {
        scaleId: 'maj',
        scaleName: 'Major',
        transpose: -12,
        score: 91.2,
        pitchCoverage: 0.9,
        weightedCoverage: 0.88,
        rangeFit: 0.8,
        contourFit: 0.95,
        tonalFit: 0.9,
        meanPitchError: 0.5,
        octaveFolds: 14,
      },
      {
        scaleId: 'min',
        scaleName: 'Minor',
        transpose: -9,
        score: 88.4,
        pitchCoverage: 0.87,
        weightedCoverage: 0.85,
        rangeFit: 0.79,
        contourFit: 0.93,
        tonalFit: 0.7,
        meanPitchError: 0.6,
        octaveFolds: 15,
      },
    ],
    parts: 1,
    engineVersions: { arrangement: '1.0.0', encoder: '1.0.0' },
  },
  decisions: [
    {
      sourceIndex: 0,
      operations: ['transpose'],
      original: { midi: 72, name: 'C5', seconds: 0 },
      output: { midi: 60, name: 'C4', seconds: 0, position: '2-2' },
      pitchDelta: -12,
      timingDelta: 0,
      reason: 'Shifted with the whole song so it fits the chosen scale.',
      cost: 0,
      importance: 0.82,
      removed: false,
    },
    {
      sourceIndex: 2,
      operations: ['transpose', 'octave_fold'],
      original: { midi: 91, name: 'G6', seconds: 1.25 },
      output: { midi: 67, name: 'G4', seconds: 1.25, position: '3-1' },
      pitchDelta: -24,
      timingDelta: 0,
      reason: "Moved by an octave to fit the Shawzin's range.",
      cost: 1,
      importance: 0.9,
      removed: false,
    },
    {
      sourceIndex: 1,
      operations: ['remove'],
      original: { midi: 76, name: 'E5', seconds: 0.625 },
      output: null,
      pitchDelta: 0,
      timingDelta: 0,
      reason: 'Removed: this passage was denser than the Shawzin can play.',
      cost: 1,
      importance: 0.3,
      removed: true,
    },
  ],
  scaleCandidates: [],
  phrases: [
    { index: 0, startSeconds: 0, endSeconds: 15, noteCount: 40, boundaryStrength: 1 },
    { index: 1, startSeconds: 16, endSeconds: 30, noteCount: 33, boundaryStrength: 0.8 },
  ],
  outputNotes: [],
  liveEvents: [
    { at: 0, fret: '2', string: '2' },
    { at: 0.625, fret: '3', string: '1' },
  ],
  parts: [],
  splitReasons: [],
  tab: 'Scale: Major',
  engineVersion: '1.0.0',
  structure: {
    segments: [
      {
        index: 0, startSeconds: 0, endSeconds: 12, durationSeconds: 12, label: 0,
        repetitions: 1, energy: 0.4, density: 2.1, recognizability: 0.42, role: 'intro',
      },
      {
        index: 1, startSeconds: 12, endSeconds: 30, durationSeconds: 18, label: 1,
        repetitions: 2, energy: 0.9, density: 3.4, recognizability: 0.94, role: 'chorus',
      },
    ],
    hookIndex: 1,
    hook: {
      index: 1, startSeconds: 12, endSeconds: 30, durationSeconds: 18, label: 1,
      repetitions: 2, energy: 0.9, density: 3.4, recognizability: 0.94, role: 'chorus',
    },
    backend: 'events',
  },
  musicProfile: {
    notesPerSecond: 2.4, peakNotesPerSecond: 6, meanPolyphony: 1.2, maxPolyphony: 3,
    chordFraction: 0.18, meanGapSeconds: 0.42, medianPitch: 72, lowFraction: 0.05,
    sustainFraction: 0.2, noteCount: 73,
  },
  shawzinSuggestions: [
    {
      variantId: 'dax', name: "Dax's Shawzin", score: 86.0, polyphony: 'polyphonic',
      timbre: 'Shamisen - bright, percussive, short decay',
      reasons: ['Plays all three strings together.', "A shamisen's attack keeps a busy line crisp."],
      warnings: [], notesLost: 0,
    },
    {
      variantId: 'corbu', name: 'Corbu Shawzin', score: 54.0, polyphony: 'monophonic',
      timbre: 'Electric guitar with overdrive - sustained and gritty',
      reasons: ['Overdriven guitar suits sustained lines.'],
      warnings: ['Monophonic: every chord becomes a fast arpeggio.'], notesLost: 12,
    },
  ],
};

export const instrumentFixture: InstrumentDto = {
  baseMidi: 48,
  variant: {
    id: 'dax',
    name: "Dax's Shawzin",
    polyphony: 'polyphonic',
    clef: 'treble',
    tuningCents: 0,
    noteLengthSeconds: 2,
    supportsAltNotes: false,
    chordType: 'dual',
  },
  variants: [
    {
      id: 'dax',
      name: "Dax's Shawzin",
      polyphony: 'polyphonic',
      clef: 'treble',
      tuningCents: 0,
      noteLengthSeconds: 2,
      supportsAltNotes: false,
      chordType: 'dual',
    },
    {
      id: 'corbu',
      name: 'Corbu Shawzin',
      polyphony: 'monophonic',
      clef: 'treble',
      tuningCents: 0,
      noteLengthSeconds: 10,
      supportsAltNotes: true,
      chordType: 'dual',
    },
  ],
  format: {
    ticksPerSecond: 16,
    maxSongSeconds: 240,
    maxTicks: 3840,
    maxNotes: 1000,
    chatLinkMaxNotes: 100,
    tickSeconds: 0.0625,
  },
  maxSimultaneousStrings: 3,
  overallRange: [48, 75],
  scales: [
    {
      id: 'pmin',
      code: '1',
      index: 0,
      name: 'Pentatonic Minor',
      chordType: 'dual',
      rootPitchClass: 0,
      intervals: [0, 3, 5, 7, 10],
      lowestMidi: 48,
      highestMidi: 75,
      pitchClasses: [0, 3, 5, 7, 10],
      notes: [],
      chords: [],
    },
    {
      id: 'maj',
      code: '5',
      index: 4,
      name: 'Major',
      chordType: 'dual',
      rootPitchClass: 0,
      intervals: [0, 2, 4, 5, 7, 9, 11],
      lowestMidi: 48,
      highestMidi: 67,
      pitchClasses: [0, 2, 4, 5, 7, 9, 11],
      notes: [],
      chords: [],
    },
  ],
};

export const environmentFixture: EnvironmentDto = {
  app: { app: '0.1.0' },
  python: '3.12.8',
  platform: 'Windows-11',
  ffmpeg: { available: true, version: 'ffmpeg 7.1', source: 'imageio', hasFfprobe: false },
  librosa: true,
  gpu: { cuda: true, device: 'NVIDIA GeForce RTX 4080 SUPER', torch: '2.14.0' },
  transcribers: [
    { id: 'basic_pitch', name: 'Basic Pitch (polyphonic)', available: true, polyphonic: true },
    { id: 'cqt', name: 'Built-in multi-pitch (CQT)', available: true, polyphonic: true },
  ],
  separators: [
    { id: 'demucs', name: 'Demucs (htdemucs)', available: true },
    { id: 'none', name: 'No separation (full mix)', available: true },
  ],
  cacheBytes: 1_500_000,
  generatedAt: '2026-01-01T00:00:00',
};

export const keymapFixture: KeymapDto = {
  keymap: {
    bindings: {
      string1: '1',
      string2: '2',
      string3: '3',
      fret1: 'left',
      fret2: 'down',
      fret3: 'right',
      whammy: 'space',
      scale: 'tab',
      emergencyStop: 'escape',
    },
    timing: {
      playback_offset_ms: 0,
      fret_to_string_ms: 12,
      inter_string_ms: 4,
      key_hold_ms: 14,
      countdown_seconds: 3,
    },
  },
  labels: {
    string1: '1st String',
    string2: '2nd String',
    string3: '3rd String',
    fret1: 'Sky Fret',
    fret2: 'Earth Fret',
    fret3: 'Water Fret',
    whammy: 'Whammy',
    scale: 'Change Scale',
    emergencyStop: 'Emergency Stop',
  },
  defaults: {
    string1: '1',
    string2: '2',
    string3: '3',
    fret1: 'left',
    fret2: 'down',
    fret3: 'right',
    whammy: 'space',
    scale: 'tab',
    emergencyStop: 'escape',
  },
  problems: [],
};
